[package]
name = "ic-concurrent"
version = "0.0.1"
description = "Run several async processes concurrently, with a limit on the number of processes running at the same time."
repository = "https://github.com/vporton/ic-concurrent"
keywords = [ "async", "parallel", "execution", "performance", "speed", "thread", "process", "fiber" ]
license = "MIT"